hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
	hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
	hl.exec_cmd("waybar-runner.py")
	hl.exec_cmd("toggle-touchpad startup")
	hl.exec_cmd("swaybg -i ~/Pictures/8DQ.jpg")
	hl.exec_cmd("ghelper")
	hl.exec_cmd("udiskie -s")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("vicinae server")
end)
