cursor #e8e1dd
cursor_text_color #cbc5c1

foreground            #e8e1dd
background            #151311
selection_foreground  #372f24
selection_background  #d2c4b4
url_color             #d7c4ab

color0   #151311
color1   #f7786f
color2   #7cd76b
color3   #ffe772
color4   #ccb69a
color5   #63533e
color6   #d7c4ab
color7   #e1dbd4
color8   #8b8781
color9   #ffa59f
color10  #b4ffa5
color11  #ffefa5
color12  #ecdac3
color13  #ffefda
color14  #fff4e7
color15  #fffcf8
